apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-tcp # do not change this name, as it is also mentioned in ingress-nginx deployment
  namespace: ingress-nginx # namespace where ingress-nginx is deployed  
data:
  "1514": wazuh/wazuh-workers:1514
  "1515": wazuh/wazuh:1515
